// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BugCore.Infrastructure.Data;

#nullable disable

namespace BugCore.Infrastructure.Migrations;

[DbContext(typeof(BugCoreDbContext))]
[Migration("20260921000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        // Identity and BugCore Models defined here
#pragma warning restore 612, 618
    }
}
