// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using BugCore.Infrastructure.Data;

#nullable disable

namespace BugCore.Infrastructure.Migrations;

[DbContext(typeof(BugCoreDbContext))]
public class BugCoreDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
#pragma warning restore 612, 618
    }
}
